import{a as L,S as w,i as a}from"./assets/vendor-73qhTu8_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v="55660188-792f1fef602df37d72b3dd925";async function u(r,e){return(await L.get("https://pixabay.com/api/",{params:{key:v,q:r,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".load-more"),S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const e=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${o.likes}</p>
        <p><b>Views</b> ${o.views}</p>
        <p><b>Comments</b> ${o.comments}</p>
        <p><b>Downloads</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",e),S.refresh()}function q(){f.innerHTML=""}function y(){document.querySelector(".loader").classList.add("visible")}function p(){document.querySelector(".loader").classList.remove("visible")}function g(){m.classList.add("visible")}function c(){m.classList.remove("visible")}const P=document.querySelector(".form"),M=document.querySelector(".load-more");let n=1,i="";const b=15;P.addEventListener("submit",$);M.addEventListener("click",B);async function $(r){if(r.preventDefault(),i=r.target.elements["search-text"].value.trim(),!i){a.error({message:"Please enter a search query!"});return}n=1,q(),c(),y();try{const e=await u(i,n);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(e.hits);const o=Math.ceil(e.totalHits/b);n<o?g():(c(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Something went wrong!"})}finally{p()}}async function B(){n+=1,c(),y();try{const r=await u(i,n);h(r.hits);const e=Math.ceil(r.totalHits/b);n>=e?(c(),a.info({message:"We're sorry, but you've reached the end of search results."})):g(),O()}catch{a.error({message:"Something went wrong!"})}finally{p()}}function O(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
